name: Festive Testing
# workflow for our festive five project, triggered on pushes to the repo.

on: [ push ]

jobs:
  build-and-run:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update packages on linux and install sfml
        run: sudo apt-get update && sudo apt-get install libsfml-dev


      - name: Create bin
        run: cd ./FinalProject/project && mkdir bin
      - name: Build project makefile
        run: cd ./FinalProject/project/bin && cmake ..
      - name: Run program
        run: cd ./FinalProject/project/bin && make

      - name: Setup headless x11 window
        run: sudo apt-get install xvfb xorg xauth openbox # xorg is needed to set DISPLAY variable later
      - name: Run graphical application tests in headless mode
        run: cd ./FinalProject/project/bin && xvfb-run --server-args="-screen 0 1024x768x24" ./App_Test
      - name: Run cppcheck
        run: sudo apt-get install cppcheck && cd ./FinalProject/project && cppcheck ./src/*.cpp
